Repository fga-eps-mds/2020.2-Anunbis, pull requests merged in 2021-05, with the labels that each got.

#188 #138 Denuncia de Comentário
  app/controller/__init__.py
  app/controller/report_resources.py
  app/model/post.py
  app/model/professor.py
  app/model/report.py
  app/model/student.py
  app/schemas/report_schema.py
  app/services/report_services.py
  database/database.sql
  tests/flask_base_tests_cases.py
  tests/tests_report.py
  tests/tests_student.py
Labels: Developers, backend

#192 #135 Aluno ver avaliacoes que realizou
  app/controller/post_resources.py
  app/schemas/post_schema.py
  app/services/post_services.py
  app/services/student_services.py
  tests/tests_post.py
Labels: Developers, backend

#190 #181 Testes de Qualidade
  .codeclimate.yml
  .config/pycodestyle
  .env
  .github/workflows/main.yml
  .github/workflows/style.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  app/app.py
  app/config.py
  app/controller/__init__.py
  app/controller/home_resources.py
  app/controller/post_resources.py
  app/controller/professor_resources.py
  app/controller/report_resources.py
  app/controller/student_resources.py
  app/ext/auth.py
  app/ext/cors.py
  app/ext/database.py
  app/model/__init__.py
  app/model/course.py
  app/model/discipline.py
  app/model/post.py
  app/model/professor.py
  app/model/report.py
  app/model/student.py
  app/model/user.py
  app/schemas/__init__.py
  app/schemas/discipline_schema.py
  app/schemas/login_schema.py
  app/schemas/post_schema.py
  app/schemas/professor_schema.py
  app/schemas/report_schema.py
  app/schemas/student_schema.py
  app/services/__init__.py
  app/services/course_services.py
  app/services/discipline_services.py
  app/services/login_services.py
  app/services/post_services.py
  app/services/professor_services.py
  app/services/report_services.py
  app/services/student_services.py
  app/services/user_services.py
  docker-compose.yml
  lint.sh
  run.py
  tests.sh
  tests/flask_base_tests_cases.py
  tests/tests_course.py
  tests/tests_home.py
  tests/tests_login.py
  tests/tests_post.py
  tests/tests_professor.py
  tests/tests_report.py
  tests/tests_student.py
  tox.ini
Labels: DevOps, Developers

#194 #178 Atualizar backlog
  docs/produto/backlog.md
Labels: Product Owner, documentation

#197 Documentação da sprint 11
  docs/sprints/planejamento-sprint-11.md
  docs/sprints/revisao-sprint-11.md
  mkdocs.yml
Labels: Scrum Master, documentation

#199 #136 Adicionando testes do get do PostList para usuario professor
  tests/tests_post.py
Labels: DevOps, Developers, backend

#195 #189 atualizar avaliacoes
  app/model/post.py
  app/model/professor.py
  app/schemas/post_schema.py
  app/schemas/professor_schema.py
  app/services/post_services.py
  database/database.sql
  tests/tests_post.py
  tests/tests_professor.py
Labels: Developers, backend

#203 #200 Deploy Continuo
  .codeclimate.yml
  .github/workflows/deploy.yml
  .github/workflows/style.yml
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  app/app.py
  app/ext/migrate.py
  app/ext/seed.py
  app/ext/static/course_discipline.json
  app/ext/static/courses.json
  app/ext/static/disciplines.json
  app/ext/static/professor.json
  app/ext/static/professor_discipline.json
  app/model/course.py
  app/model/discipline.py
  app/model/post.py
  database/database.sql
  database/seeds.sql
  docker-compose.yml
  lint.sh
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/8edb48444054_.py
  scripts/flask.sh
  scripts/lint.sh
  scripts/tests.sh
  tests/tests_seed.py
Labels: DevOps

#212 (#209) Corrigindo bug da tela inicial do professor
  app/schemas/post_schema.py
Labels: backend

#217 #204 Documentação da API
  .codeclimate.yml
  Pipfile
  Pipfile.lock
  app/app.py
  app/config.py
  app/controller/__init__.py
  app/controller/auth_resources.py
  app/controller/course_resources.py
  app/controller/home_resources.py
  app/controller/post_resources.py
  app/controller/professor_resources.py
  app/controller/report_resources.py
  app/controller/student_resources.py
  app/docs/__init__.py
  app/docs/auth.py
  app/docs/course.py
  app/docs/post.py
  app/docs/professor.py
  app/docs/report.py
  app/docs/student.py
  app/ext/swagger.py
  tests/tests_home.py
Labels: Developers, backend

#222 #218 Atualizar documento de arquitetura
  docs/documentacao/documento-de-arquitetura.md
  docs/images/casosDeUso.png
  docs/images/diagramaEntidadeRelacionamento.png
  docs/images/diagramaLogicoDados.png
  docs/images/diagramaPacotesBackEnd.png
  docs/images/diagramaPacotesFrontEnd.png
Labels: documentation

#223 #207 Alimentar o Banco de Dados
  app/ext/seed.py
  app/static/seeds/course_discipline.json
  app/static/seeds/courses.json
  app/static/seeds/disciplines.json
  app/static/seeds/professor.json
  app/static/seeds/professor_discipline.json
  migrations/versions/e85ce4de86e4_.py
  tests/tests_seed.py
Labels: Developers, backend

#225 Documentando o post mortem
  docs/post_mortem.md
  mkdocs.yml
Labels: documentation
