Repository fga-eps-mds/2020.2-Anunbis, pull requests merged in 2021-03, with the labels that each got.

#45 #42 Atualização do documento de Arquitetura
  docs/documentacao/documento-de-arquitetura.md
  docs/images/arquiteturaMVCBackEnd.png
Labels: Product Owner, documentation

#46 #44 atualizando nome do projeto
  CONTRIBUTING.md
  README.md
  docs/documentacao/roadmap.md
  docs/sprints/planejamento-sprint-0.md
  docs/sprints/planejamento-sprint-1.md
  docs/sprints/planejamento-sprint-2.md
  docs/sprints/planejamento-sprint-3.md
  docs/sprints/planejamento-sprint-template.md
  mkdocs.yml
Labels: documentation

#47 #43 Criado o Documento de Metodologia utilizadas
  docs/documentacao/documento-de-metodologias.md
  mkdocs.yml
Labels: Scrum Master, documentation

#48 Revisando documento de arquitetura e corrigindo src
  docs/documentacao/documento-de-arquitetura.md
Labels: Developers, bug, documentation

#50 Adicionando o tópico React no documento de arquitetura
  docs/documentacao/documento-de-arquitetura.md
Labels: documentation, frontend

#49 Protótipo de Baixa Fidelidade e Fluxo de Usuário
  docs/images/fluxoDeUsuario.png
  docs/produto/prototipos.md
  mkdocs.yml
Labels: Creative, documentation, frontend

#53 Política de Repositório
  docs/CODE_OF_CONDUCT.md
  docs/como_contribuir.md
  docs/policies/branches.md
  docs/policies/commits.md
  docs/policies/issues.md
  docs/policies/pullRequests.md
  mkdocs.yml
Labels: documentation

#62 Atualizando documento de protótipo
  docs/images/fluxoDeUsuario.jpg
  docs/images/fluxoDeUsuario.png
  docs/produto/prototipos.md
Labels: documentation

#58 Atualizar Documento de Visao e Politica de Branchs
  docs/documentacao/documento-de-visao.md
  docs/policies/branches.md
Labels: documentation

#66 #37 Configurações iniciais do backend
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  docker-compose.yml
  src/app/__init__.py
  src/app/config.py
  src/app/controller/__init__.py
  src/app/model/__init__.py
  src/app/view/__init__.py
  src/database/database.sql
Labels: Developers, Em Atraso, backend

#69 #68 Revisar arquitetura backend
  Dockerfile
  src/app/__init__.py
  src/app/app.py
  src/app/blueprints/__init__.py
  src/app/blueprints/restapi/__init__.py
  src/app/blueprints/restapi/home_resources.py
  src/app/blueprints/schemas/__init__.py
  src/app/config.py
  src/app/controller/__init__.py
  src/app/ext/__init__.py
  src/app/ext/database.py
  src/app/models.py
  src/app/tests/__init__.py
Labels: Developers, backend

#71 #70 Criando Planejamento de Riscos
  docs/documentacao/planejamento-de-riscos.md
  mkdocs.yml
Labels: Scrum Master, documentation

#75 #59 Adicionando casos de usos e revisando documento de arquitetura
  docs/documentacao/documento-de-arquitetura.md
  docs/images/casosDeUso.png
  docs/images/diagramaArquitetura.png
Labels: Developers, documentation

#73 #72 Atualizando Documento de Protótipo
  docs/produto/prototipos.md
Labels: documentation

#77 #74 Modelagem dos dados
  docs/images/diagramaEntidadeRelacionamento.png
  docs/images/diagramaLogicoDados.png
  src/database/database.sql
Labels: Architect, Creative, Developers, backend

#78 #76 Criando Documento Canvas
  docs/documentacao/canvas.md
  docs/images/modeloDeNegocios.png
  mkdocs.yml
Labels: Creative, documentation

#92 #84 [US01] Cadastro de aluno
  Pipfile
  Pipfile.lock
  docker-compose.yml
  src/app/app.py
  src/app/blueprints/restapi/__init__.py
  src/app/blueprints/restapi/course_resources.py
  src/app/blueprints/restapi/home_resources.py
  src/app/blueprints/restapi/student_resources.py
  src/app/blueprints/schemas/__init__.py
  src/app/blueprints/schemas/course_schema.py
  src/app/blueprints/schemas/student_schema.py
  src/app/blueprints/services/__init__.py
  src/app/blueprints/services/course_services.py
  src/app/blueprints/services/student_services.py
  src/app/models.py
  src/app/models/__init__.py
  src/app/models/course_model.py
  src/app/models/discipline_model.py
  src/app/models/post_model.py
  src/app/models/professor_model.py
  src/app/models/report_model.py
  src/app/models/student_model.py
  src/database/database.sql
  src/database/seeds.sql
Labels: Developers, backend

#99 #98 Revisando tópicos do backlog do produto
  docs/produto/backlog.md
Labels: documentation

#105 #96 Revisar readme
  README.md
Labels: documentation

#108 #104 [US03] Realizar Login Aluno
  src/app/controller/__init__.py
  src/app/controller/login_resources.py
  src/app/model/services/login_services.py
  src/app/model/services/student_services.py
  src/app/view/login_schema.py
Labels: Developers, backend

#106 #101 [US13] e [US14] Cadastro de Avaliação
  src/app/controller/__init__.py
  src/app/controller/post_resources.py
  src/app/model/dao/discipline_dao.py
  src/app/model/dao/post_dao.py
  src/app/model/dao/professor_dao.py
  src/app/model/entity/post.py
  src/app/model/services/discipline_services.py
  src/app/model/services/post_services.py
  src/app/model/services/professor_services.py
  src/app/model/services/student_services.py
  src/app/view/post_schema.py
  src/app/view/student_schema.py
  src/database/database.sql
  src/database/seeds.sql
Labels: Developers

#107 #102 [US05] Buscar professor por parte do nome
  src/app/config.py
  src/app/controller/__init__.py
  src/app/controller/professor_resources.py
  src/app/model/dao/post_dao.py
  src/app/model/dao/professor_dao.py
  src/app/model/dao/student_dao.py
  src/app/model/services/professor_services.py
  src/app/model/services/student_services.py
  src/app/view/discipline_schema.py
  src/app/view/post_schema.py
  src/app/view/professor_schema.py
  src/app/view/student_schema.py
  src/database/database.sql
Labels: Developers

#111 Document/#100 Revisado Roadmap e aba das sprints
  docs/documentacao/documento-de-arquitetura.md
  docs/documentacao/documento-de-visao.md
  docs/documentacao/roadmap.md
  docs/index.md
  docs/sprints/planejamento-sprint-0.md
  docs/sprints/planejamento-sprint-1.md
  docs/sprints/planejamento-sprint-2.md
  docs/sprints/planejamento-sprint-3.md
  docs/sprints/planejamento-sprint-4.md
  docs/sprints/planejamento-sprint-5.md
  docs/sprints/revisao-sprint-0.md
  docs/sprints/revisao-sprint-1.md
  docs/sprints/revisao-sprint-2.md
  docs/sprints/revisao-sprint-3.md
  docs/sprints/revisao-sprint-4.md
  docs/sprints/revisao-sprint-5.md
  docs/sprints/revisao-sprint-template.md
  mkdocs.yml
Labels: Product Owner, Scrum Master, documentation

#110 #97 Revisar documento de arquitetura
  docs/documentacao/documento-de-arquitetura.md
  docs/images/Diagrama_Pacotes_BackEnd.png
  docs/images/Diagrama_Pacotes_FrontEnd.png
  docs/images/diagramaEntidadeRelacionamento.png
  docs/images/diagramaLogicoDados.png
Labels: documentation

#109 #91 [US02] Cadastro de Professor
  src/app/controller/__init__.py
  src/app/controller/professor_resources.py
  src/app/model/dao/post_dao.py
  src/app/model/dao/professor_dao.py
  src/app/model/entity/professor.py
  src/app/model/services/professor_services.py
  src/app/model/services/student_services.py
  src/app/view/professor_schema.py
  src/database/database.sql
Labels: Developers, backend

#118 #116 Revisando documentação da wiki
  docs/CODE_OF_CONDUCT.md
  docs/como_contribuir.md
  docs/documentacao/documento-de-arquitetura.md
  docs/documentacao/documento-de-metodologias.md
  docs/documentacao/documento-de-visao.md
  docs/documentacao/planejamento-de-riscos.md
  docs/documentacao/roadmap.md
  docs/documentacao/termo-de-abertura.md
  docs/index.md
  docs/policies/branches.md
  docs/policies/issues.md
  docs/policies/pullRequests.md
  docs/produto/backlog.md
  docs/produto/prototipos.md
  docs/sprints/planejamento-sprint-0.md
  docs/sprints/planejamento-sprint-2.md
  docs/sprints/planejamento-sprint-3.md
  docs/sprints/planejamento-sprint-4.md
  docs/sprints/revisao-sprint-0.md
  docs/sprints/revisao-sprint-1.md
  docs/sprints/revisao-sprint-2.md
  docs/sprints/revisao-sprint-3.md
  docs/sprints/revisao-sprint-4.md
  docs/sprints/revisao-sprint-5.md
Labels: Product Owner, documentation
