Repository fga-eps-mds/2020.2-Anunbis, pull requests merged in 2021-04, with the labels that each got.

#145 Criação do documento de identidade visual
  docs/produto/identidade-visual.md
  mkdocs.yml
Labels: Creative, Product Owner, documentation

#147 Revert 145 document/#121 identidade visual
  docs/produto/identidade-visual.md
Labels: Creative, Product Owner, documentation

#146 Atualizando documento Canvas
  docs/documentacao/canvas.md
  docs/images/modeloDeNegocios.png
  docs/images/modeloDeNegocios3.png
Labels: Product Owner, documentation

#149 Configurando deploy da aplicação no heroku
  .env
  Pipfile
  Pipfile.lock
  Procfile
  docker-compose.yml
  run.py
  src/__init__.py
  src/app/config.py
  src/app/model/dao/course_dao.py
  src/app/model/dao/discipline_dao.py
  src/app/model/dao/post_dao.py
  src/app/model/dao/professor_dao.py
  src/app/model/dao/report_dao.py
  src/app/model/dao/student_dao.py
  src/app/model/services/login_services.py
  src/app/model/services/professor_services.py
  src/database/database.sql
  src/database/seeds.sql
Labels: enhancement

#153 Documentação da Sprint 8
  docs/sprints/planejamento-sprint-8.md
  docs/sprints/revisao-sprint-8.md
  mkdocs.yml
Labels: Scrum Master, documentation

#155 #152 Configurando ambiente para testes unitarios
  Dockerfile
  Pipfile
  Pipfile.lock
  app/__init__.py
  app/app.py
  app/config.py
  app/controller/__init__.py
  app/controller/course_resources.py
  app/controller/home_resources.py
  app/controller/login_resources.py
  app/controller/post_resources.py
  app/controller/professor_resources.py
  app/controller/student_resources.py
  app/ext/__init__.py
  app/ext/auth.py
  app/ext/cors.py
  app/ext/database.py
  app/model/__init__.py
  app/model/dao/__init__.py
  app/model/dao/course_dao.py
  app/model/dao/discipline_dao.py
  app/model/dao/post_dao.py
  app/model/dao/professor_dao.py
  app/model/dao/report_dao.py
  app/model/dao/student_dao.py
  app/model/entity/__init__.py
  app/model/entity/course.py
  app/model/entity/post.py
  app/model/entity/professor.py
  app/model/entity/student.py
  app/model/services/__init__.py
  app/model/services/course_services.py
  app/model/services/discipline_services.py
  app/model/services/login_services.py
  app/model/services/post_services.py
  app/model/services/professor_services.py
  app/model/services/student_services.py
  app/view/__init__.py
  app/view/course_schema.py
  app/view/discipline_schema.py
  app/view/login_schema.py
  app/view/post_schema.py
  app/view/professor_schema.py
  app/view/student_schema.py
  database/database.sql
  database/seeds.sql
  docker-compose.yml
  run.py
  tests/__init__.py
  tests/tests_flask_api.py
  tox.ini
Labels: DevOps

#156 #154 Autenticando rotas
  app/controller/course_resources.py
  app/controller/post_resources.py
  app/controller/professor_resources.py
Labels: backend

#159 Bugfix/#158 multiplas classes tests
  app/controller/__init__.py
  app/controller/course_resources.py
  app/controller/home_resources.py
  app/controller/login_resources.py
  app/controller/post_resources.py
  app/controller/professor_resources.py
  app/controller/student_resources.py
  tests/flask_base_tests_cases.py
Labels: DevOps, bug

#160 #157 Testes das Rotas
  app/controller/__init__.py
  app/controller/course_resources.py
  app/controller/home_resources.py
  app/controller/login_resources.py
  app/controller/post_resources.py
  app/controller/professor_resources.py
  app/controller/student_resources.py
  app/model/dao/post_dao.py
  app/model/entity/course.py
  app/model/entity/discipline.py
  app/model/services/course_services.py
  app/model/services/post_services.py
  app/view/course_schema.py
  tests/flask_base_tests_cases.py
  tests/tests_course.py
  tests/tests_login.py
  tests/tests_post.py
  tests/tests_professor.py
  tests/tests_student.py
Labels: DevOps, Developers

#163 #161 Testes no GitHub Actions
  .github/workflows/main.yml
Labels: DevOps

#164 Refatorando Documento de Visão
  docs/documentacao/documento-de-visao.md
Labels: Product Owner, Scrum Master, documentation

#166 [US22] Modificar senha do aluno
  app/controller/student_resources.py
  app/model/dao/student_dao.py
  app/model/services/student_services.py
  tests/tests_student.py
Labels: backend, enhancement

#172 Atualizando o documento de arquitetura
  docs/documentacao/documento-de-arquitetura.md
  docs/images/Diagrama_Pacotes_BackEnd.png
  docs/images/Diagrama_Pacotes_FrontEnd.png
Labels: Product Owner, Scrum Master, documentation

#177 [US19] Feature/#137 avaliar comentario de terceiros
  app/controller/post_resources.py
  app/controller/professor_resources.py
  app/model/post.py
  app/model/student.py
  app/schemas/post_schema.py
  app/schemas/professor_schema.py
  app/schemas/student_schema.py
  app/services/post_services.py
  tests/tests_post.py
  tests/tests_professor.py
  tests/tests_student.py
Labels: Developers, backend, frontend

#176 Documentação da sprint 9
  docs/sprints/planejamento-sprint-9.md
  docs/sprints/revisao-sprint-9.md
  mkdocs.yml
Labels: Scrum Master, documentation

#182 Documentação da Sprint 10
  docs/sprints/planejamento-sprint-10.md
  docs/sprints/revisao-sprint-10.md
  mkdocs.yml
Labels: Scrum Master, documentation

#183 Atualização do protótipo de alta fidelidade
  docs/documentacao/documento-de-arquitetura.md
  docs/images/diagramaPacotesBackEnd.png
  docs/images/diagramaPacotesFrontEnd.png
  docs/images/fluxoDeUsuario.jpg
  docs/produto/prototipos.md
Labels: Creative, frontend
